"""Service layer for the generated project."""
from typing import List, Optional

from fastapi import FastAPI, HTTPException, Query
from fastapi.middleware.cors import CORSMiddleware

from .models import Assistant, AssistantCreate, AssistantUpdate
from .store import store

app = FastAPI(
    title="AI Part Lookup Assistant API",
    version="0.1.0",
    description="REST API for AI Part Lookup Assistant. Generated by the Agentic SDLC workflow.",
    docs_url="/docs",
    openapi_url="/openapi.json",
    openapi_tags=[
        {"name": "health", "description": "Liveness probe used by the deploy pipeline."},
        {"name": "assistants", "description": "Assistants managed by this service."},
    ],
)

# The UI is a separate App Service, so it is a cross-origin caller.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)


@app.get("/health", tags=["health"])
def health() -> dict:
    return {"status": "ok"}


@app.get("/api/assistants", response_model=List[Assistant], tags=["assistants"])
def list_items(status: Optional[str] = Query(default=None)) -> List[dict]:
    return store.list(status)


@app.post("/api/assistants", response_model=Assistant, status_code=201, tags=["assistants"])
def create_item(body: AssistantCreate) -> dict:
    return store.create(body.model_dump())


@app.get("/api/assistants/{item_id}", response_model=Assistant, tags=["assistants"])
def get_item(item_id: int) -> dict:
    item = store.get(item_id)
    if item is None:
        raise HTTPException(status_code=404, detail="Assistant not found")
    return item


@app.patch("/api/assistants/{item_id}", response_model=Assistant, tags=["assistants"])
def update_item(item_id: int, body: AssistantUpdate) -> dict:
    item = store.update(item_id, body.model_dump())
    if item is None:
        raise HTTPException(status_code=404, detail="Assistant not found")
    return item


@app.delete("/api/assistants/{item_id}", status_code=204, tags=["assistants"])
def delete_item(item_id: int) -> None:
    if not store.delete(item_id):
        raise HTTPException(status_code=404, detail="Assistant not found")
